import Head from "next/head";
import cookie from "js-cookie";
import styles from "../styles/Home.module.css";

export default function Home({ token }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Client And Server Side Cookies</h1>
        <h2>Token: {token}</h2>
        <div className={styles.btnwrapper}>
          <button
            type="button"
            onClick={() => {
              fetch("/api/login", {
                method: "post",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ token: "ABCD" }),
              });
            }}
          >
            Login
          </button>
          <button
            type="button"
            onClick={() => {
              fetch("/api/logout", {
                method: "post",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({}),
              });
            }}
          >
            Logout
          </button>
        </div>
      </main>
    </div>
  );
}

export function getServerSideProps({ req, res }) {
  return { props: { token: req.cookies.token || "" } };
}
